image: node:12

stages:
  - pre
  - test
  - publish
  - post

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - npm run generate-dotenv
  - npm install


# Lint the code to make sure it is quality
lint:
  tags:
    - docker
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^master/
  script:
    - npm run lint

lint:code-formatter:
  tags:
    - docker
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^master/
  script:
    - npm run code-formatter-check

# # Ignore types for now
# lint:types:
#   tags:
#     - docker
#   stage: test
#   only:
#     - merge_requests
#   except:
#     variables:
#       - $CI_COMMIT_REF_NAME =~ /^master/
#   script:
#     - yarn types-check


# Run tests to ensure the code works
tests:unit:
  tags:
    - docker
  stage: test
  only:
    - merge_requests
  except:
    variables:
      - $CI_COMMIT_REF_NAME =~ /^master/
  script:
    - npm run tests --silent

# tests:coverage:
#   tags:
#     - docker
#   stage: test
#   only:
#     - master
#   script:
#     - npm run coverage --silent
#   coverage: /All\sfiles.*?\s+(\d+.\d+)/
